name: Build binary

on:
  push:
    branches: [ "testnewci" ]
  pull_request:
    branches: [ "testnewci" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get toolchain from cache
      id: cache-toolchain
      uses: actions/cache/restore@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: prefix-${{hashFiles('scripts/create_devenv.py')}}
    - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      name: Install prefix
      id: install_prefix
      run: python scripts/create_devenv.py scripts/dls scripts/prefix
    - name: Build binary
      run: python scripts/build.py -j0
    - uses: actions/upload-artifact@v3
      with:
        name: th06e
        path: |
          build/th06e.exe
          build/th06e.pdb
    - if: always() && steps.cache-toolchain.outputs.cache-hit != 'true' && steps.install_prefix.outcome == 'success'
      name: Save toolchain to cache
      uses: actions/cache/save@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: ${{ steps.cache-toolchain.outputs.cache-primary-key }}

  build-diff:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get toolchain from cache
      id: cache-toolchain
      uses: actions/cache/restore@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: prefix-${{hashFiles('scripts/create_devenv.py')}}
    - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      name: Install prefix
      id: install_prefix
      run: python scripts/create_devenv.py scripts/dls scripts/prefix
    - name: Build binary
      run: python scripts/build.py -j0 --build-type diffbuild
    - uses: actions/upload-artifact@v3
      with:
        name: th06e-diff
        path: |
          build/th06e.exe
          build/th06e.pdb
    - if: always() && steps.cache-toolchain.outputs.cache-hit != 'true' && steps.install_prefix.outcome == 'success'
      name: Save toolchain to cache
      uses: actions/cache/save@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: ${{ steps.cache-toolchain.outputs.cache-primary-key }}

  build-dll:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get toolchain from cache
      id: cache-toolchain
      uses: actions/cache/restore@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: prefix-${{hashFiles('scripts/create_devenv.py')}}
    - if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' }}
      name: Install prefix
      id: install_prefix
      run: python scripts/create_devenv.py scripts/dls scripts/prefix
    - name: Build binary
      run: python scripts/build.py -j0 --build-type dllbuild
    - uses: actions/upload-artifact@v3
      with:
        name: th06e-dll
        path: |
          build/th06e.dll
          build/th06e.pdb
    - if: always() && steps.cache-toolchain.outputs.cache-hit != 'true' && steps.install_prefix.outcome == 'success'
      name: Save toolchain to cache
      uses: actions/cache/save@v3
      with:
        # A directory to store and save the cache
        path: scripts/prefix
        # An explicit key for restoring and saving the cache
        key: ${{ steps.cache-toolchain.outputs.cache-primary-key }}
