name: Compare reimplementation

on:
  workflow_run:
    workflows: [Build binary]
    types: [completed]
  workflow_dispatch:
    inputs:
      workflow_id:
        required: true
        type: number

jobs:
  compare:
    runs-on: windows-latest

    permissions:
      statuses: write
      contents: write

    steps:
    - name: Report tests check
      if: ${{ github.event_name == 'workflow_run' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.workflow_run.head_sha,
            state: 'pending',
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: 'Comparison checks',
            context: 'comparison-checks',
          })
    - uses: actions/checkout@v3
    - name: Install satsuki
      uses: robinraju/release-downloader@v1.8
      with:
        repository: happyhavoc/satsuki
        latest: false
        tag: v0.1.2
        fileName: x86_64-windows-satsuki.exe
    - name: Add satsuki to prefix
      run: python scripts/create_devenv.py --only satsuki scripts/dls scripts/prefix
    - name: Download original game binary for comparison
      run: |
        curl -L $env:ORIGINAL_URL -o resources/game.exe
        $hash = (Get-FileHash resources/game.exe).Hash
        if ($hash -ne "9f76483c46256804792399296619c1274363c31cd8f1775fafb55106fb852245") {
          Write-Host "Downloaded file with unexpected hash."
          Write-Host "Expected: 9f76483c46256804792399296619c1274363c31cd8f1775fafb55106fb852245"
          Write-Host "Got: $hash"
          exit 1
        }
      env:
        ORIGINAL_URL: ${{ secrets.ORIGINAL_URL }}
    - name: Download reimplemented game binary for comparison (1/2)
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: context.payload.workflow_run ? context.payload.workflow_run.id : context.payload.inputs.workflow_id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "th06e-diff"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: matchArtifact.id,
             archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/th06e.zip`, Buffer.from(download.data));
    - name: Download reimplemented game binary for comparison (2/2)
      run: |
        mkdir -p build
        unzip th06e.zip -d build
    - name: Use implemented.csv from target repo
      run: curl -L https://raw.githubusercontent.com/${{github.event.workflow_run.head_repository.full_name}}/${{github.event.workflow_run.head_sha}}/config/implemented.csv -o config/implemented.csv
    - name: Use mapping.csv from target repo
      run: curl -L https://raw.githubusercontent.com/${{github.event.workflow_run.head_repository.full_name}}/${{github.event.workflow_run.head_sha}}/config/mapping.csv -o config/mapping.csv
    - name: Create diff summary
      run: python scripts/diff_all_functions.py > $env:GITHUB_STEP_SUMMARY
    - name: Create diff SVG
      run: python scripts/update_decompile_stats.py gen_svg
    - name: Download UploadTool
      run: curl -L https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh -o upload.sh
    - name: Upload Progress SVG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash ./upload.sh resources/progress_dark.svg resources/progress.svg
    - name: Report tests check
      if: ${{ github.event_name == 'workflow_run' && success() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.workflow_run.head_sha,
            state: 'success',
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: 'Comparison checks',
            context: 'comparison-checks',
          })
    - name: Report tests check
      if: ${{ github.event_name == 'workflow_run' && failure() }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.workflow_run.head_sha,
            state: 'failure',
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: 'Comparison checks',
            context: 'comparison-checks',
          })
